language: r
dist: xenial

branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin

before_install:
- npm install netlify-cli -g

script:
  - Rscript -e 'blogdown::install_hugo()'
  - Rscript -e 'blogdown::build_site()'

after_success:
- netlify deploy --prod --dir public

deploy:
  provider: script
  script: netlify deploy --dir public --prod --message "$DEPLOY_MSG"
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

# This is a combination between https://github.com/rstudio-education/stat545-reboot/issues/1 and https://bookdown.org/yihui/blogdown/travis-github.html